#!/usr/bin/env bash

MACHINE="$(basename ${0})"
if [ -n "${1}" ]; then
	MACHINE="${1}"
fi

ENV="$(docker-machine env "${MACHINE}" 2> /dev/null)"
if [ ${?} -eq 0 ]
then
	eval "${ENV}"
	export DOCKER_VERSION=$(docker-machine version "${MACHINE}")
else
	export DOCKER_TLS_VERIFY=
	export DOCKER_HOST=
	export DOCKER_CERT_PATH=
	export DOCKER_MACHINE_NAME=
	export DOCKER_VERSION="system"
fi

clear

CHECK_PROFILE=$(osascript -e 'tell application "Terminal" to get settings sets whose name is "'${MACHINE}'"')
if [ -n "${CHECK_PROFILE}" ]
then
	CURRENT_PROFILE=$(osascript -e 'tell front window of application "Terminal" to get name of current settings of selected tab')
	osascript -e 'tell application "Terminal" to set current settings of front window to settings set "'${MACHINE}'"'
fi

${SHELL} -l
clear

if [ -n "${CHECK_PROFILE}" ]
then
	osascript -e 'tell application "Terminal" to set current settings of front window to settings set "'${CURRENT_PROFILE}'"'
fi
